v1.6 fix glibc 2.39 extract

diff --git a/xclibc b/xclibc
--- a/xclibc
+++ b/xclibc
@@ -313,17 +313,24 @@ extract() {
     if [[ $# -ne 2 ]]; then
         usage_extract
     fi
-    local deb=$1
+    local deb=`readlink -f $1`
     local out=$2
     if [ ! -d "$out" ]; then
         mkdir $out
     fi
     local tmp=`mktemp -d`
-    dpkg -x $deb $tmp || die "dpkg failed"
-
+    cd $tmp
+    ar xv $deb || die "ar failed"
+    if [ -f "data.tar.zst" ];then
+        tar -I zstd -xf data.tar.* || die "tar failed"
+    else
+        tar xf data.tar.* || die "tar failed"
+    fi
+    cd -
 
     cp -rP $tmp/lib/*/* $out 2>/dev/null \
       || cp -rP $tmp/lib32/* $out 2>/dev/null \
+      || cp -rP $tmp/usr/lib/*/* $out 2>/dev/null \
       || cp -rP $tmp/usr/lib/debug/lib/*/* $out 2>/dev/null \
       || cp -rP $tmp/usr/lib/debug/lib32/* $out 2>/dev/null \
       || cp -rP $tmp/usr/lib/debug/.build-id $out 2>/dev/null \
@@ -933,7 +940,7 @@ do
         fi
         ;;
         v)
-        echo "xclibc v1.5"
+        echo "xclibc v1.6"
         echo "------------------------"
         echo "|Update based on xclibc|"
         echo "|Writen by E4L4        |"
